# Generated by Django 5.0.6 on 2024-10-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(default='2024-10-06', verbose_name='Data conta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(db_index=True, default='2024-10-06', verbose_name='Data transação'),
        ),
    ]
