# Generated by Django 5.0.6 on 2024-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_address_alter_transaction_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bairro',
            field=models.CharField(default='', max_length=50, verbose_name='Bairro'),
        ),
    ]
