# Generated by Django 5.0.6 on 2024-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(default='2024-10-07', verbose_name='Data conta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(db_index=True, default='2024-10-07', verbose_name='Data transação'),
        ),
    ]
