# Generated by Django 5.0.6 on 2024-10-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='aprovada',
            field=models.BooleanField(default=False, verbose_name='Aprovada'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='area',
            field=models.IntegerField(choices=[(1, 'Administração e gestão'), (2, 'Alimentos e bebidas'), (3, 'Construção civil e design'), (4, 'Moda Têxtil, calçados e joalheria'), (5, 'Papel, celulose, gráfica, editorial'), (6, 'Mecânica industrial'), (7, 'Logistica e transporte'), (8, 'Automotiva'), (9, 'Mecâtronica, automação e energia'), (10, 'Meio ambiente, saúde e segurança do trabalho'), (11, 'Metalurgia e soldagem'), (12, 'Química cerâmica e plásticos'), (13, 'Refrigeração e climatização'), (14, 'Tecnologia da informação'), (15, 'Outras')], default=15, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='atividades',
            field=models.CharField(default='', max_length=100, verbose_name='Atividades'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contato',
            field=models.CharField(default='', max_length=50, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='empresa',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requisitos',
            field=models.CharField(default='', max_length=100, verbose_name='Requisitos'),
        ),
    ]
