# Generated by Django 5.0.6 on 2024-10-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_transaction_address_remove_transaction_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salário'),
        ),
    ]
