# Generated by Django 5.0.6 on 2024-10-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='slug',
        ),
    ]
